AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"

Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
